var iMatrixMessage={"deleteInfo":"Are you sure delete？",
		"updateInfo":"Are you sure update？",
		"selectInfo":"Please select a record",
		"selectOneInfo":"Please select a record",
		"selectOneDataInfo":"Please select a record",
		"selectOnlyOneInfo":"Please select only a record",
		"download":"Download",
		"delete":"Delete",

		"thisCode":"This Code",
		"code":"Code ",
		"exist":"exist",
		"serverInfo":"Server busy, please try again later",
		
		"common.required":"Required",
		"department.longest30Characters":"longest 30 characters",
		"department.longest60Characters":"longest 60 characters",
			

		"department.codeFail":"Code cannot contain symbols",
		"department.Spaces":"Spaces",
		"department.departmentNameNotContainesSpaces":"Before and after the department name cannot contain Spaces",
		"department.abbreviationNameNotContainesSpaces":"Before and after the abbreviation cannot contain Spaces",

		"department.departmentCodeRepeat":"Department code repeat",
		"department.departmentNameRepeat":"Department name repetition",
		"department.branchCodeRepeat":"Branch code duplication",
		"department.branchNameRepeat":"Branch name repetition",
		"department.branchNameAndGroupRepeat":"Branch name cannot repeat with group",
		"department.branchAbbreviationNameRepeat":"Branches or repetition",
		"department.branchCodeAndGroupCodeRepeat":"Branch code and group code repetition",

		"department.error":"Error",
		"department.isValidateAndWait":"Is to validity check of department name, please wait",
		"department.selectDepLeft":"Please select a department in a tree on the left",

		"department.deleteChildDepFirst":"Please delete child department or branch",
		"department.deleteBranchDep":"First remove branch department, staff, working group under the branch, branch, authorization management, role",
		"department.sureDeleDep":"Sure you want to delete the department",
		"department.sureDeleBranch":"Sure you want to delete the branch",

		"department.branchesAcrossCandidates":"You have branches across the candidates, if continue to perform the original branch would not exist",
		"department.loginNameBelow":"The following user login name",
		"department.baranchHasExist":"The current existing branches, has been automatic filtering, can not be added",
		"department.selectDepLefNode":"Please select a branch node in the tree on the left",
		"department.selectRemoveUser":"Please select a user to remove",

		"user.seleteUser":" please select the user",
		"common.departmentManager":"Department manager",
			
			
		"thisCode":"This code: ",
		"exist":" exist",
		"serverInfo":"Server busy, please try again later",
		"selectCustomFirstMenuInfo":"Please select the first menu of custom system!",
		"selectCustomFirstMenuStateInfo":"Please select the start or draft first menu of custom system!!",
		"deleteDraftMenuInfo":"To ensure system normal run,only can delete the draft menu!",
		"menuExistInfo":"This menuCode existed",
		"formCodeIncludeInfo":"formCode only can't include  special character except underline!",
		"onlineVesionInfo":"To ensure system normal run,the vesion's updating function has shielded",
		"shieldStartOrStopInfo":"To ensure system normal run, the 【start/forbidden】 has shielded",
		"exportSystemAllFormInfo":"Export all the current system's forms?",
		"deleteCompleteFormInfo":"It not noly will be delete relevant jsp、workFlowInstance、workFlowDefinition,but also delete relevant list、dataTable、DataBase table、data authorization、 data classification,are you sure delete thoroughly!",
		"saveSuccess":"Save successfully!",
		"menuMoveInfo":"Don't move this menu to portal system",
		"selectOneFatherMenuInfo":"Please select a Father Menu!",
		"menuManager.newMenuInfo":"Don't new menu under this placeholder!",
		"menuManager.updateUrlCacheCallbackInfo":"Update url cache successfully",
		"menuManager.importMenuColorboxTitle":"Import Menu",
		"menuManager.importCustomSystemColorboxTitle":"Import custom system",
		"menuManager.validatePortalTip":"Don't new menu under this portal!",
		"menuManager.createMenuColorboxTitleTip":"Create menu",
		"menuManager.createSystemColorboxTitleTip":"Create system",
		"menuManager.selectOneMenuInfo":"Please select a Menu!",
		"menuManager.selectOneMenuInfo":"Menu started,can't update",
		"menuManager.deleteFirstMenuValidate":"You Can't delete Started first menu!",
		"menuManager.updateMenu":"Update menu",
		"menuManager.casInstruction":"If cas Login，iMatrix  platform will be add ticket parameter after menu link,this menu of system must validate that whether the ticket is implemented by the valid interface method!",
		"menuManager.required":"Required",
		"menuManager.importSuccess":"Import Success!",
		"menuManager.importValidate":"Please select import file!",
		"menuManager.confirmCover":"Are you sure to confirm cover?",
		"menuManager.digitRequired":"Please input digit",
		"menuManager.imageInfo":"Image(png,jpg,gif)",
		
		"formManager.confirmClosePage":"Confirm Close Page？",
		"formManager.saveItem":"Save Item",
		"formManager.createForm":"Create form",
		"formManager.copyForm":"Copy form",
		"formManager.validateMaxLength":"Max length is 500!",
		"formManager.importFormViewColorboxTitle":"Import form",
		"formManager.importFormValidate":"Please select a file to import",
		"formManager.updateTemplate":"Update template",
		"formManager.deleteDraftInfo":"To ensure system running normally,only can delete the draft record state!",
		"formManager.setOrCancelInfo":"Are you sure set/cancelDefault?",
		"formManager.copyView":"CopyView",
		"formManager.updateInfo":"To ensure system running normally,only can update Demo system or custum System",
		"formManager.validateDigit":"Please enter multi digit split by comma.",
		"formManager.cancelFreezeValidate":"Please first cancel groupHeader and you can set the freeze column numbers",
		"formManager.importListValidate":"Import List",
		"formManager.exportInfo":"Are you sure export all list of system?",
		"formManager.exportTableInfo":"Are you sure export all data table of system?",
		"formManager.deleteTableInfo":"This will be delete page of associated,are you sure delete?",
		"formManager.cancelfreezeInfo":"Please cancel freeze columns and then set the groupHeader!",
		"formManager.saveBaseInfo":"Please save basicInfo first!",
		"formManager.saveColumnInfo":"Please save dataSheet first and you can set column information!",
		"formManager.saveGenerateCodenfo":"Please save dataSheet first and you can set generate code information!",
		"formManager.chooseFatherClass":"Choose Father",
		"formManager.workFlowCodeValidate":"Please enter workflow code!",
		"formManager.chooseDraftValidate":"To ensure system running normally,only can choose the draft record state!",
		"formManager.updateSheetValidate":"To ensure system running normally,you can't update the started or forbidden data sheet!",
		"formManager.importDateSheet":"Import",
		"formManager.delelteAssociateAll":"this will delete associated list、form、page,are you sure delete?",
		"formManager.delelteStartForbiddenInfo":"To ensure system running normally,you can't delete started and forbidden data table",
		"formManager.fileValidate":"Please choose a file!",
		"formManager.maxUpload":"Please choose upload file(max length 200k)",
		"formManager.choosePicture":"Please choose a picture",
		"formManager.inputGt20":"Please input digit with >= 20",
		"formManager.inputGt50":"Please input digit with >= 50",
		"formManager.chooseDateSource":"Please choose data source",
		"formManager.listHeaderValidate":"Please input list control header or field",
		"formManager.addSetValidate":"Please add field set",
		"formManager.databaseFieldValidate":"Please database field",
		"formManager.mapControlNameValidate":"Input mapped control name",
		"formManager.addValidate":"Added alerady",
		"pageManager.urgentInfo":"Please insert urgent level words decription",
		"pageManager.flagInfo":"Please choose corresponding flag",
		"formManager.selectFieldInfo":"Please choose corresponding field",
		"formManager.specialFieldInfo":"Please choose special field",
		"formManager.conclusionSource":"Conclusion Source",
		"formManager.validateSuccess":"Validate successfully!",
		"formManager.optionInfo":"Please choose optionGroup!",
		"formManager.optionInfo.title":"Choose Option Group",
		"formManager.property":"Property",
		"formManager.delete":"Delete",
		"formManager.notContainInfo":"Not contain space,double quote or single quote",
		"formManager.formExist":"Form name exist",
		"formManager.lengthError":"Length error,required and maxLength is 100",
		"formManager.insertComplateKey":"Please input full key-value before add!",
		"fckeditor.deleteTextField":"Are you sure to delete this TextField?",
		"fckeditor.deleteTextAreaField":"Are you sure to delete this TextArea?",
		"fckeditor.deleteCalField":"Are you sure to delete this Calendar?",
		"fckeditor.deleteDepartPerField":"Are you sure to delete this DepartPerson?",
		"fckeditor.deleteSignField":"Are you sure to delete this Signature?",
		"fckeditor.deleteCalculateField":"Are you sure to delete this Calculate?",
		"fckeditor.deleteSelectField":"Are you sure to delete this Select?",
		"fckeditor.deleteDataField":"Are you sure to delete this DataGet?",
		"fckeditor.deleteUrgentField":"Are you sure to delete this UrgencyLevel?",
		"fckeditor.deleteSpecialField":"Are you sure to delete this Special Controller?",
		"fckeditor.deleteSpecialSelectField":"Are you sure to delete this Special Select person?",
		"fckeditor.deleteCustomField":"Are you sure to delete this CustomList?",
		"fckeditor.deleteStandardField":"Are you sure to delete this StandardList?",
		"fckeditor.deleteButtonField":"Are you sure to delete this Button Controller?",
		"fckeditor.deleteAttachField":"Are you sure to delete this Special AttachUpload?",
		"fckeditor.deletePictureField":"Are you sure to delete this PictureUpload?",
		"fckeditor.deleteJsField":"Are you sure to delete this JavaScript/CSS?",
		"fckeditor.deletePictureUploadField":"Are you sure to delete this PictureUpload?",
		"fckeditor.deleteHongField":"Are you sure to delete this Macro controller?",
		"fckeditor.deletePlaceholderField":"Are you sure to delete this Placeholder?",
		"kindEditor.options.langType":"en",
		
		
		"pageManager.confirmStartInfo":"Are you sure to Start?",
		"pageManager.confirmEnable":"Confirm enable?",
		"pageManager.confirmDisable":"Confirm disable?",
		"pageManager.confirmRunFInfo":"To ensure system running normally,the forbidden function has shielded",
		"pageManager.confirmRunInfo":"To ensure system running normally,multiterm's start and forbidden function haave shielded",
		"pageManager.confirmStartOrForbidden":"Are you sure start/forbidden?",
		"pageManager.saveSetInfo":"Set the buttion information before save base information",
		"pageManager.savePreviewInfo":"Please save and you can preview!",
		"pageManager.selectColorboxTitle":"Select page",
		"pageManager.customZtreeTitle":"Select form list",
		"pageManager.clear":"Clear",
		
		"basicSetting.fatherValidate":"The lower level has the higher level already!",
		"basicSetting.userTree":"Organization Structure Tree",
		"basicSetting.deleteOptionGroupValidate":"Please select one optionGroup",
		"basicSetting.yes":"Yes",
		"basicSetting.no":"No",
		"basicSetting.delete":"Delete",
		"basicSetting.add":"Add",
		"basicSetting.optiongroupNameValidate":"Optiongroup name exist!",
		"basicSetting.infoValidate":"Some information inconformity",
		"basicSetting.needOptionInfo":"At least need a option",
		"basicSetting.optionNameNotNull":"Option name not null!",
		"basicSetting.optionValueNotNull":"Option value not null!",
		"basicSetting.showSort":"Show sort",
		"basicSetting.optiongroupRepeat":"Optiongroup name repeat",
		"basicSetting.optiongroupAnd":"And",
		"basicSetting.optionlengthValidate":"Length error,rqueired and maxLength is 25",
		"basicSetting.optionSpace":"Can't include space,double marks or single quotes",
		"basicSetting.optionCorrect":"Correct",
		"basicSetting.optionCodeExist":"Code Exist",
		"basicSetting.importRowInsertValidate":"Please enter noninteger(exclude 0)",
		"basicSetting.importColorboxTitle":"Import",
		"basicSetting.selectLanguage":"Choose Language",
		"basicSetting.registerInfo":"User has registered!",
		"basicSetting.uploadValidateInfo":"Please save form first and then upload picture!;",
		"basicSetting.uploadMaxLength":"Click here to upload image(maxLength is 30MB)",
		"basicSetting.dataSourceConfigure":"DataSource configure",
		"basicSetting.enableInfo":"In order to ensure normal system demonstration, can't delete the enabled for",
		"interfaceManager.dataSourceDriverInfo":"Please write dataSource driver",
		"interfaceManager.testSuccess":"Test successfully",
		"interfaceManager.testFail":"Test Failture:",
		"interfaceManager.address":"[address]",
		"interfaceManager.dataBase":"[database]",
		"interfaceManager.ordinaryInferace":"Ordinary interface",
		"interfaceManager.confrimStartOrForbidden":"Are you sure Start/Forbidden",
		"interfaceManager.sourceCodeValidate":"This DataSource code exist",
		"interfaceManager.rtxValidate":"RTX Reminder max length is 1000,it's length is ",
		"interfaceManager.messageValidate":"Short message reminder max length is 1000,it's length is ",
		"interfaceManager.officerValidate":"Officer reminder max length is 490,it's length is ",
		"interfaceManager.specificPerson":"Please choose seecific person",
		"deleteSuccess":"Delete successfully",
		"interfaceManager.configure":"Configure",
		"interfaceManager.smsgatewayNew":"Sms Gateway new",
		"interfaceManager.smsgatewayUpdate":"Sms Gateway update",
		"interfaceManager.gatewayValidate":"Custom gateway,please insert implement class",
		"interfaceManager.gatewayCodeExist":"This gateway code exist!",
		"messagePlatform.smsTemplateNew":"Sms template new",
		"messagePlatform.smsTemplateUpdate":"Sms template update",
		"messagePlatform.chooseTemplate":"Choose Template",
		"messagePlatform.chooseRequestValidate":"Request choosed,callback url need to choose!",
		"basicSetting.onlyOneOptionInfo":"Only one default option",
		"messagePlatform.sendReceiveSetNew":"Receive-Send set new",
		"messagePlatform.sendReceiveSetUpdate":"Receive-Send set update",
		
		
	////////////////////////////////////////////////////////////////////////////
		
		"common.pleaseSelect":"Please choose",
		"common.pleaseSelectOne":"Only choose one！",
		"workgroup.sureDeleteWorkGroup":"Deleting a workgroup is determined？",
		"workgroup.noSelectedUser":"No user selected！",
		"workgroup.defaultCodeLonest27":"The default number exceeds the maximum length of 27",
		"workgroup.codeNotContainsSpace":"Before and after the code cannot contain Spaces!",
		"workgroup.workgroupNameNotContainsSpace":"Workgroup name cannot contain Spaces before and after!",
		"workgroup.codeNotContainsfuhao":"Code can't contain symbol!",
		"workgroup.workgroupCodeRepeat":"Repeat working group number!",
		"workgroup.workgroupNameRepeat":"Workgroup name repeat!!",
		"workgroup.isValidatewgCode":"Is to validity check of group number, please wait...",
			
		"ldap.synchronousUserInfo":"Synchronous userInfo",
		"ldap.synchronousOrganizationalStructure":"Synchronous organizational structure",
		"ldap.example":"For example",
		"authorization.addRole":"Adding roles",
		"authorization.noAuthAddRole":"No permission for this branch add role!",
		"authorization.noAuthAddManager":"No permission for this branch add administrator!",
		"user.selectStaff":"Select a staff",
		"user.notAddAllUserManager":"Can not add to all the users in the company to branch manager",
		
		"authorization.selectDelete":"Please select remove items!",
		"authorization.sureDeleteSeledted":"Sure you want to remove the option?",
		"authorization.noAuthRemoveUserAndRole":"No permission to move under the other branches of personnel and role!",
		
		"authorization.pleaseSelectRole":"Please select a role",
		"authorization.sureDeleteSelectedItems":"Sure you want to removed from the role of the options?",
		"authorization.selectDep":"Choose department",
		"authorization.selectWorkGroup":"Select the working group",
		"authorization.defaultManagerCannotDelete":"The system default administrator cannot be deleted!",
		"authorization.showAuth":"Check the permissions",
		"authorization.enumConfig":"Please config Enum url in dataTableManager!",
		"authorization.enumConfigAddress":"Please config Enum access adress in dataTableManager!",
		
		////
		
		"authorization.importRole":"Import role function relationship",
		"authorization.importRoleUserContion":"Import role user relationship",
		
		"authorization.selectSystem":"Please select a system!",
		"authorization.noAuthUpdateRole":"No permission to modify this role!",
		"authorization.selectUpdateRole":"Please select a role to modify",
		"authorization.sureDelete":"Sure you want to delete?",
		"authorization.selectDeleteRole":"Please select a character to delete",
		"authorization.threeRoleCannotDelete":"Three characters are not allowed to delete ",
		"authorization.addResources":"Add the resource",
		"authorization.selectRoleToAddResources":"Please select a role to add resources",
		"authorization.selectRoleToDeleteResources":"Please select a role to remove resources",
		
		"authorization.removeResources":"Remove resources",
		"authorization.showResources":"Query resources",
		"authorization.selectBranchs":"Please select a subordinate branch!",
		"authorization.defaultCodeLonest23":"The default number exceeds the maximum length of 23",
		"authorization.roleCodeRepeat":"Repeat character number!",
		"authorization.roleNameRepeat":"Character name repeat!",
		"authorization.roleNameNotContainesParentheses":"Character name cannot contain brackets!",
		"authorization.cannotCopyAuth":"Can't copy the security administrator, system administrators, branch, audit administrator, the administrator permissions",
		"authorization.cannotCopyAuthManager":"Can't copy the workflow administrator, process definition administrator permissions",
		"authorization.selectRole":"Select role",
		"authorization.sureCopyAuth":"Determine the copy permissions?",
		"authorization.sureCopyAuthSuccess":"The reproduction success",
		"authorization.eq":"Equal",
		"authorization.noteq":"Not Equal",
		"authorization.contain":"Contain",
		"authorization.notContain":"Not Contain",
		"authorization.null":"Is Empty",
		"authorization.notNull":"Is Not Empty",
		"authorization.gt":"Gt",
		"authorization.lt":"Lt",
		"authorization.gteq":"Gt And Eq",
		"authorization.lteq":"Lt And Eq",
		"authorization.select":"--Select--",

		"log.sureDelete":"Sure to delete？",
		"log.nowDelete":"Deleting...",
		"log.noResultExport":"No results can be exported",		
		"log.sureDeleteAll":"Sure all deleted?",
		

		"dataAuth.selectSystem":"Please select the corresponding system!",
		"dataAuth.selectPerson":"Please select a user",
		"dataAuth.selectDataAuth":"Please select operation permissions",
		"dataAuth.selectDatas":"Please select a record",
		"dataAuth.onlySelectOneData":"Can only choose one record",
		"dataAuth.codeIsExist":"The authorization number has been in existence",
		"dataAuth.dataTable":"The data table",
		"dataAuth.role":"Role",

		"dataAuth.selectDataClassification":"Please select the corresponding data classification.",
		"dataAuth.parenthesisDoesNotMatch":"'left parenthesis' and' right parenthesis' does not match!",//
		"dataAuth.selectContionType":"The selection criteria type first!",
		"dataAuth.showContion":"Check the condition",
		
		
		"permission.listTables":"List tables：",
		
		"permission.selectDataTables":"Please select the data table",
		"permission.selectDataTypes":"Please select data classification!",
		"permission.selectlistTables":"Please select a list",
		"permission.selectCorrespondingMenu":"Please select the corresponding menu",
		"permission.saveFailCodeIsExist":"Save failed, the serial number has been in existence",
		
		"permission.defaultCodeLonest27":"The default number exceeds the maximum length of 27",
		"permission.codeNotContainsSpace":"Cannot contain Spaces before and after the coding!",
		"permission.selectOneData":"Please select a data",
		"permission.onlySelectOneData":"Can only choose a data",
		"permission.pleaseSelectData":"Please select a data",
		"permission.deleteSuccess":"Delete successfully",
		"permission.sureUpdateDatatables":"Determine the modify data table? The selected rule conditions will be deleted!",
		"permission.pleaseSelectform":"Please choose the form!",
		"permission.contionNotLonest20":"Length is not greater than 20",
		"permission.contionFail":"Conditions cannot contain Spaces, single quotes, double quotes and braces",
		"permission.cannotDeleteCode":"In order to ensure normal system demonstration, can't delete the Numbers for",
		"permission.and":"And",
		"permission.data":"data!",
		"permission.updateTables":"Please amend the authorized corresponding list quickly",
		
		"menu.ldap":"LDAP integration",
		"menu.imatrix":"Since platform integration",
		"menu.rtx":"RTX integration",
		"menu.other":"Other ways to integrate",
		"authorization.selectContion":"Please select the query conditions",
		"authorization.selectExport":"Please select the export items",
		
		"acs.theFatherCannot":"The father cannot choose the Department department!",
		"acs.canNotCross":"Can not cross the branch to choose the parent department, please select again!",
		"acs.pleaseDeleteThe":"Please delete the Department, staff, working group, branch office, branch office authority management, role",
		"acs.cannotSetThe":"Cannot set the current sub sector for the parent department department!",
		"acs.youHaveCross":"You have cross branches, please re select!",
		"acs.pleaseSelectDepartment":"Please select department!",
		"acs.pleaseSelectDepartment.colorboxTitle":"Please Select Department",
		"acs.user":"User:",
		"acs.alreadyExists":"already exists in the branch of your choice, cannot be added, the system will automatically filter.",
		"acs.areReplacingThe":"Are replacing the department chief and part-time department is not a branch, if continue to replace the user department part-time empty. Are you sure you want to change?",
		
		
		
		//////////////工作流/////////////////
		//菜单
		"wf.menu.extendedTask":"Extended Task",
		"wf.menu.currentTask":"Current Task",
		"wf.menu.archivingTask":"Archiving Task",
		"wf.menu.extendedStatistics":"Extended Statistics",
		"wf.menu.myCommission":"My Commission",
		"wf.menu.myFiduciary":"My Fiduciary",
		//js方法
		"wf.engine.selectProcess":"Please select a process",
		"wf.engine.selectLink":"Select Link",
		"wf.engine.pleaseSelectLink":"Please select link",
		"wf.engine.choosePeople":"Select Users",
		"wf.engine.delegate.pleaseSelect":"Please select",
		"wf.engine.delegate.beyond500Words":"Beyond 500 words",
		"wf.engine.delegate.theMaximum":"The maximum input 500 words, you have entered",
		"wf.engine.delegate.error":"Error",
		"wf.engine.processHasBeen":"Process has been deployed, will add a new version?",
		"wf.engine.selectSpecificType":"Please select a specific type",
		"wf.engine.selectTemplate":"Select Template",
		"wf.engine.doYouConfirm":"Do you confirm the cancellation of these instances?",
		"wf.engine.confirmTheMandatory":"Confirm the mandatory end of these examples?",
		"wf.engine.pathIsNotCorrect":"Path is not correct",
		"wf.engine.thereIsNo":"There is no emergency plan for this process",
		"wf.engine.processHasChange":"Process has ended or has been canceled, can not change the person",
		"wf.engine.theProcessAdd":"The process has ended or has been canceled, can not be added to the person",
		"wf.engine.theProcessReduced":"The process has ended or has been canceled, can not be reduced for people",
		"wf.engine.confirmTheSuspension":"Confirm the suspension of these instances?",
		"wf.engine.confirmToContinue":"Confirm to continue with these examples?",
		"wf.engine.details":"Details",
		"wf.engine.transferTaskList":"Transfer Task List",
		"wf.engine.batchRemoveTask":"Batch Remove Tasks",
		"wf.engine.choose":"Choose",
		"wf.engine.linkJumpSuccess":"Link jump success",
		"wf.engine.query":"Query",
		"wf.engine.areYouSure":"Are you sure you remove these instances?",
		"wf.engine.referenceToThe":"Reference to the type of data dictionary created will also be deleted, confirm the delete it?",
		"common.allPersonnel":"All Personnel",
		"common.allDepartment":"All Department",
		"common.allWorkgroup":"All Workgroup",
		"wf.engine.hasBeenAll":"Has been all the staff, please clear and then add",
		"wf.engine.noManager":"No Manager",
		"wf.engine.removeManager":"Remove Manager",
		"wf.engine.enterInteger":"Please enter an integer",
		"wf.engine.pleaseEnterANumber":"Please enter a number greater than or equal to 1",
		"wf.engine.numberExists":"The number already exists",
		"wf.engine.selectionProcess":"Selection process and links",
		"wf.engine.process":"Process",
		"wf.engine.operation":"Operation",
		"wf.engine.processTypeEncoding":"Process type encoding!",
		"wf.engine.parameter":"Parameter",
		"wf.engine.allFiles":"All Files",
		"wf.engine.pleaseSaveThis":"Please save this form first, then upload the template!",
		"wf.engine.goWrong":"Go wrong!",
		"wf.engine.youUploadThe":"You upload the file too much.",
		"wf.engine.uploadFileSize":"Upload file size of 0 bytes",
		"wf.engine.uploadFilesOut":"Upload files out of size limits!",
		"wf.engine.numberOfFiles":"Number of files that are allowed to be uploaded more than once, each time the number of files to be uploaded is",
		"wf.engine.invalidFileType":"Invalid file type!",
		"wf.engine.isUploading":"Is uploading...",
		"wf.engine.successfullyLoaded":"Successfully loaded to upload queue",
		"wf.template.clickOnThe":"Click on the upload template file (max 30MB)",
		"wf.text.pleaseSelectATask":"Please select a task",
		"wf.text.canNotChoose":"Can not choose the current aspects of other management",
		"wf.text.CannottGetRid":"Can't get rid of all the people",
		"wf.text.mustFillIn":"Must fill in the comments",
		
		"role.add.resources.successful.role":"Add resources successful role",
		"role.role.successfully.remove.resources":"Role successfully remove resources",
		"role.please.select.a.resource":"Please select a resource!",
		"determine.the.close.small.window":"Determine the close small window?",
		"updatePassWord.alterPassword":"Alter pass word",
		
		"common.cc.personnel":"Cc personnel",
		"common.task.assignments":"Task Assignments",
		"common.successful.operation":"Successful Operation!",
		"common.please.select.the.next.tache":"Please select the next tache!",
		"common.choose.to.deal.with.people":"Choose to deal with people",
		"common.selectionProcess":"Selection Process",
		"common.select.add.counter.personnel":"Select Add Counter Personnel",
		"common.select.delete.counter.personnel":"Select Delete Counter Personnel",
		"portal.sorry.widget.erro":"Sorry,Widget Erro!",
		"delegatemain.carte.blanche":"Carte Blanche",
		"delegatemain.authority.delegation":"Authority Delegation",
		"common.pleaseChooseAndCanOnlyChooseOne":"Please choose and can only choose one",
		
		"mm.setting.exist":"The system setting existing,please update!",
		
		"ftl.PleaseFillIn":"Please fill in the comments",
		"ftl.theControlOf":"The control of a stored opinion does not exist",
		"syn.ldap.info":"Ldap integration mode has enabled a single sign on, to confirm the current integration method to open a single sign on?",
		"syn.rtx.info":"Rtx integration mode has enabled a single sign on, to confirm the current integration method to open a single sign on?",
		"syn.other.info":"Other integration mode has enabled a single sign on, to confirm the current integration method to open a single sign on?",
		"portal.param.item.count.max":"Display the number can not be more than 500!",
		"portal.param.item.count.input":"Please enter the number of display!",
		"portal.param.item.count.number":"Please enter a number!",
		"edit.widget":"Edit",
		"cancel.edit.widget":"Cancel Edit",
		"close.widget":"Close",
		"collapse.widget":"Collapse",
		"extend.widget":"Extend",
		"common.submit.success":"Submit success",
		"common.select.group":"Please select workgroup!",
		"rankSelectTitle":"Organizational structure tree",
		"common.please.save.first":"Please save first",
		"mms.urgency.level":"Urgency level",
		"mms.whether.teshiteban":"Whether teshiteban",
		//基础设置系统
		"bs.newTimingSettings":"New Timing Settings",
		"bs.modifyTimingSettings":"Modify Timing Settings",
		"bs.addTiming":"Add Timing",
		"permission.item.type.user":"Personnel",
		"permission.item.type.department":"Department",
		"permission.item.type.role":"Role",
		"permission.item.type.workgroup":"Working Group",
		"permission.item.type.currentUserSuperiorDepartment":"The current user superior departments",
		"permission.item.type.currentUserTopDepartment":"The current user's top division",
		"permission.item.type.currentUserDirectSuperiorId":"Immediate superior",
		"permission.item.type.currentUserDirectSuperiorDepartment":"Immediate superior departments",
		"permission.item.type.currentUserDirectSuperiorRole":"The role of immediate supervisor",
		"permission.item.type.currentUserDirectSuperiorWorkgroup":"Immediate superior working group",
		"permission.item.type.all.user":"All the people",
		"operator.text.et":"Equal",
		"operator.text.et.not":"Not Equal",
		"condition.operator.and":"And",
		"condition.operator.or":"Or",
		"mms.cannotSelectMenu":"Cannot select menu, select Page",
		"mms.pleaseSelectPage":"Please Select Page",
		"wf.theEffectiveDate":"The effective date should be less than the closing date",
		"wf.effectiveDateShould":"Effective date should be greater than or equal to the current date",
		"wf.closingDateShould":"Closing date should be greater than the effective date",
		"wf.closingDateCurrent":"Closing date should be greater than the current date",
		"task.assign.success.info":"The task has been successfully assigned",
		"common.text.file.error.info":"Please save first,upload again!",
		"common.opinion.error.info":"Please fill in the opinion",
		"common.attache.delete.confirm.info":"Are you sure you want to delete the attachment?",
		"acs.data.rule.pleaseAField":"Please a field!",
		"formManager.currentTime":"Current Time",
		"formManager.assignTime":"Assign Time",
		"formManager.currentDate":"Current Date",
		"formManager.assignDate":"Assign Date",
		"common.opinion.fill":"Please fill in your opinion!",
		"acs.data.rule.pleaseSelectAConditionValue":"Please select a condition value!",
		"acs.data.rule.pleaseEnterAConditionValue":"Please enter a condition value!",
		"acs.data.rule.pleaseSelectAStandardValue":"Please select a standard value!",
		"acs.data.rule.pleaseFillInBeanName":"Please fill in beanName!",
		"acs.data.rule.pleaseChooseTheRightNode":"Please choose the right node!",
		"formManager.optionSource":"Option Source",
		"bs.jobCornSettingDeclare.explain":"Explain",
		"bs.jobInfo.youEnteredIsNotValid":"You entered is not valid",
		"bs.jobInfo.fieldEmailReminder":"Field Email Reminder can only enter 1000 characters, the current length of ",
		"bs.jobInfo.fieldRtxReminder":"Field RTX Reminder can only enter 1000 characters, the current length of ",
		"bs.jobInfo.fieldMessageReminder":"Field Message Reminder can only enter 1000 characters, the current length of ",
		"bs.jobInfo.fieldOfficerReminder":"Field Officer Reminder can only enter 1000 characters, the current length of ",
		"bs.jobInfo.pleaseEnterAnIntegerBelowSevenBits":"Please enter an integer below 7 bits",
		"bs.jobInfo.pleaseEnterAnIntegerGreaterThanOne":"Please enter an integer greater than 1",
		"common.PleaseUploadTheFileMaxHundredMB":"Please upload the file (max 100MB)",
		"list.view.isRequired":" is required!",
		"list.view.reservedWordPleaseReEnter":"Is a reserved word, please re-enter!",
		"shielding.function.prompt":"In order to ensure the normal demonstration of the system, shielding the function.",
		"authority.pleaseSelectStandardValue":"Please select standard value!",
		"mms.enterTheValueOverRange":"Enter the value over range",
		"mms.buttonSettingsNotTurnPage":"【Button Settings】in this page does not add this button to turn the page!",
		"mms.thereIsNoCorrespondingList":"There is no corresponding list, do not need to return.",
		"portal.pleaseEnterTheQueryCondition":"Please enter the query condition",
		"dataRule.pleaseSelectDataClassification":"Please select data classification!",
		"dataRule.pleaseSelect":"Please select!",
		"task.thereIsOnlyOneManagerNoNeedToSign":"There is only one manager, no need to sign",
		"task.receiveAnError":"Receive an error",
		"task.toGiveUpToGetAnError":"To give up to get an error",
		"task.pleaseSelectTheFileToImport":"Please select the file to import!",
		"wf.shieldingDeleteFunction":"In order to ensure the system's normal presentation, when the process definition is enabled or disabled,Shielding the 【Delete】 function.",
		"wf.shieldingModifyBasicPropertiesFunction":"In order to ensure the system's normal presentation, when the process definition is enabled or disabled,Shielding the 【Modify basic properties】 function."
};
