var portal_lang={'messageOpenTitle':'个人消息管理',
				  'baseSettingTitle':'个人设置',
				  'registerWidgetTitle':'注册小窗体',
				  'addWidgetTitle':'添加小窗体',
				  'addThemeTitle':'添加主题',
				  'addWebPageTitle':'添加页签',
				  'updateWebPageTitle':'修改页签',
				  'delPageTip':'您确定要删除页签吗？',
				  'freshWidgetTip':'抱歉，动态刷新小窗体有误！',
				  'noWidgetParameterTip':'该小窗体没有参数'};
